# Autogenerated wrapper script for tree_sitter_julia_jll for i686-w64-mingw32
export libtreesitter_julia

JLLWrappers.@generate_wrapper_header("tree_sitter_julia")
JLLWrappers.@declare_library_product(libtreesitter_julia, "libtreesitter_julia.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_julia,
        "bin\\libtreesitter_julia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
